### ISSUE TITLE
how to install this as npm module not found

### ISSUE THREAD

**Issue by gmchaturvedi1** [luxp/jqmath#1]
How to install npm module not found

**Comment by luxp** [comment]
You can try `npm install https://github.com/luxp/jqmath`.

**Comment by gmchaturvedi1** [comment]
thanks install done but still i am facing problem, iam using reactjs so when i embed top container in parsemath itis showing _renderContainer errotr

**Comment by luxp** [comment]
I didn't test this with reactjs. Reactjs is using virtual dom, which may not compatible with jqMath.

**Comment by luxp** [comment]
@gmchaturvedi1 I just published this module，now you can install it using `npm install --save jqmath`
