### ISSUE TITLE
Converting MathML input

### ISSUE THREAD

**Issue by jotaf98** [luxp/jqmath#9]
Hi, first of all, great work with this library!

Since it uses MathML internally, I was wondering if it's possible to pass that in instead of text?

Basically, the goal is to use jqMath as a polyfill for Chrome's lack of MathML support. MathJax is slow; there's another [nice alternative](https://github.com/pshihn/math-ml) but its formatting doesn't look as good as jqMath's.

**Comment by luxp** [comment]
I think it's possible, but I'm not very professional about it. This source code is from https://mathscribe.com/author/jqmath.html and the author is dbarton@mathscribe.com. Maybe you can contact dbarton@mathscribe.com for some help or pull request is welcome. This repo currently is  just an npm wrap.
